# Generated by Django 5.0.6 on 2024-06-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codArticulo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAltaArticulo', models.DateField(auto_now_add=True)),
                ('fechaBajaArticulo', models.DateField(blank=True, max_length=30, null=True)),
                ('nombreArticulo', models.CharField(max_length=30)),
                ('stockArticulo', models.IntegerField()),
                ('puntoPedido', models.IntegerField(null=True)),
                ('stockSeguridad', models.IntegerField(null=True)),
                ('loteOptimo', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoArticulo',
            fields=[
                ('codEA', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEA', models.CharField(max_length=30)),
                ('fechaHoraBajaEA', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoOrdenCompra',
            fields=[
                ('codEC', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEC', models.CharField(max_length=30)),
                ('fechaHoraBajaEC', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoError',
            fields=[
                ('codME', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreME', models.CharField(max_length=30)),
                ('fechaBajaME', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloInventario',
            fields=[
                ('codMI', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMI', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('fechaBajaProveedor', models.DateField(blank=True, null=True)),
                ('nombreProveedor', models.CharField(max_length=30)),
                ('diasDeDemora', models.IntegerField()),
                ('precioXunidad', models.FloatField()),
                ('costo_pedido', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('codDemanda', models.IntegerField(primary_key=True, serialize=False)),
                ('demandaReal', models.IntegerField(default=0)),
                ('demandaPredecida', models.IntegerField(default=0)),
                ('mesDemanda', models.IntegerField()),
                ('anioDemanda', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='stock.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='stock.estadoarticulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='modeloInventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='stock.modeloinventario'),
        ),
        migrations.CreateModel(
            name='Prediccion_Demanda',
            fields=[
                ('codPD', models.IntegerField(primary_key=True, serialize=False)),
                ('cantPeriodos', models.IntegerField()),
                ('coeficienteSuavizacion', models.FloatField()),
                ('errorAceptable', models.FloatField()),
                ('mesPrediccion', models.IntegerField()),
                ('anioPrediccion', models.IntegerField()),
                ('demandas', models.ManyToManyField(related_name='predicciones', to='stock.demanda')),
                ('metodoError', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='stock.metodoerror')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('codODC', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fechaOrden', models.DateField(auto_now_add=True)),
                ('diasDemoraOrden', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenDeCompra', to='stock.articulo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenDeCompra', to='stock.estadoordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenDeCompra', to='stock.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='stock.proveedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codVenta', models.AutoField(primary_key=True, serialize=False)),
                ('cantVenta', models.IntegerField()),
                ('fechaVenta', models.DateField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='stock.articulo')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='stock.demanda')),
            ],
        ),
    ]
