# Generated by Django 5.0.6 on 2024-06-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion_demanda',
            name='demandas',
        ),
        migrations.AddField(
            model_name='prediccion_demanda',
            name='articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='stock.articulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='loteOptimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='puntoPedido',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stockSeguridad',
            field=models.IntegerField(default=0),
        ),
    ]
