# Generated by Django 5.0.6 on 2024-06-08 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_demanda_valordemanda_demanda_aniodemanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='stock.articulo'),
            preserve_default=False,
        ),
    ]
