# Generated by Django 5.0.6 on 2024-06-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_proveedor_articulo_articulo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='loteOptimo',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='puntoPedido',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stockSeguridad',
            field=models.IntegerField(default=None),
        ),
    ]
