# Generated by Django 5.0.6 on 2024-06-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_articulo_cantidasintervalofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cgi',
            field=models.FloatField(default=0),
        ),
    ]
