# Generated by Django 5.0.6 on 2024-06-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_demanda_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloInventario',
            fields=[
                ('codMI', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMI', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='modeloInventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='stock.modeloinventario'),
            preserve_default=False,
        ),
    ]
