# Generated by Django 5.0.6 on 2024-06-24 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_articulo_cgi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion_demanda',
            name='cantPeriodos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prediccion_demanda',
            name='coeficienteSuavizacion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediccion_demanda',
            name='metodoError',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='stock.metodoerror'),
        ),
    ]
