# Generated by Django 5.0.6 on 2024-06-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_modeloinventario_articulo_modeloinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoError',
            fields=[
                ('codME', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreME', models.CharField(max_length=30)),
                ('fechaBajaME', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='prediccion_demanda',
            name='anioPrimerPeriodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediccion_demanda',
            name='coeficienteSuavizacion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prediccion_demanda',
            name='errorAceptable',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prediccion_demanda',
            name='mesPrimerPeriodo',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='prediccion_demanda',
            name='metodoError',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='stock.metodoerror'),
            preserve_default=False,
        ),
    ]
