# Generated by Django 5.0.6 on 2024-06-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_articulo_loteoptimo_alter_articulo_puntopedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='stock.proveedor'),
        ),
    ]
