# Generated by Django 5.0.6 on 2024-06-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_metodoerror_prediccion_demanda_anioprimerperiodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion_demanda',
            name='fechaBajaDemanda',
        ),
    ]
