# Generated by Django 5.0.6 on 2024-06-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_prediccion_demanda_cantperiodos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion_demanda',
            name='errorAceptable',
            field=models.FloatField(null=True),
        ),
    ]
