# Generated by Django 5.0.6 on 2024-06-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_prediccion_demanda_fechabajademanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion_demanda',
            name='resultadoPrediccion',
        ),
    ]
